### ISSUE TITLE
Call after load?

### ISSUE THREAD

**Issue by sigmasoldi3r** [groupe-sii/cordova-plugin-device-display-metrics#2]
Calling the function `deviceMetrics.getDpi` in the base controller gives `undefined` so, loading inside a function like:

``` javascript
 $scope.newDevice = function () {
        if (device.available) {
            deviceMetrics.getDpi('', function (metrics) {
            // ...
            });
       // ...
       }
 };
```

Makes it **work**, notice that `device.available` is a value given by the plugin `cordova-plugin-device`, not sure if it affects. Also `$scope.newDevice` is called on click (using `ng-click` directive).

Never written Cordova/Phonegap plugins, if I can help I would be very happy!

PD: The script works fine, just I want to contribute to the documentation to make it clear.

**Comment by vogloblinsky** [comment]
Yes, waiting for cordova is the best trick :

``` javascript
document.addEventListener("deviceready", onDeviceReady, false);
function onDeviceReady() {
    // Now safe to use device APIs
}
```

I have updated the docs.

**Comment by sigmasoldi3r** [comment]
Awesome! thanks!!
